---
- name: Configure ELK VM with Docker
  hosts: elk
  remote_user: azdmin
  become: true
  tasks: 
    # Use apt moduel
	- name: Install docker.io
	  apt: 
	    update_cache: yes
		force_apt_get: yes
		name: docker.io
		state: present
		
	# Use apt moduel
    - name: Install python3-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    # Use pip moduel (It will default to pip3)
    - name: Install Docker moduel
      pip:
	    name: docker
		state: present
		
	# Use command moduel
    - name: Increase virtual memory
      command: sysctl -v vm.max_map_count=262144

    # Use sysctl moduel
    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present

    # Use docker_container moduel
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always

        # List the ports that ELK runs on
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044
